In [2]:
import numpy as np
import pandas as pd

In [3]:
# 1D Array
arr1 = np.array([1, 2, 3, 4, 5])
print("1D Array:")
print(arr1)
print("Shape:", arr1.shape)

# 2D Array
arr2 = np.array([[1, 2, 3],
                 [4, 5, 6]])
print("\n2D Array:")
print(arr2)
print("Shape:", arr2.shape)

# 3D Array
arr3 = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])

print("\n3D Array:")
print(arr3)
print("Shape:", arr3.shape)

1D Array:
[1 2 3 4 5]
Shape: (5,)

2D Array:
[[1 2 3]
 [4 5 6]]
Shape: (2, 3)

3D Array:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Shape: (2, 2, 2)


In [4]:
print("Original Array:")
print(arr2)

print("\nAfter Broadcasting (+10):")
print(arr2 + 10)

Original Array:
[[1 2 3]
 [4 5 6]]

After Broadcasting (+10):
[[11 12 13]
 [14 15 16]]


In [5]:
print("Original:", arr1)

print("Multiply by 2:")
print(arr1 * 2)

print("Square:")
print(arr1 ** 2)

print("Square Root:")
print(np.sqrt(arr1))

Original: [1 2 3 4 5]
Multiply by 2:
[ 2  4  6  8 10]
Square:
[ 1  4  9 16 25]
Square Root:
[1.         1.41421356 1.73205081 2.         2.23606798]


In [6]:
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

result = A @ B

print("Matrix A")
print(A)

print("\nMatrix B")
print(B)

print("\nMatrix Multiplication")
print(result)

Matrix A
[[1 2]
 [3 4]]

Matrix B
[[5 6]
 [7 8]]

Matrix Multiplication
[[19 22]
 [43 50]]


In [7]:
url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv"

df = pd.read_csv(url)

df.head()

,sepal_length,sepal_width,petal_length,petal_width,species
0,5.1,3.5,1.4,0.2,setosa
1,4.9,3.0,1.4,0.2,setosa
2,4.7,3.2,1.3,0.2,setosa
3,4.6,3.1,1.5,0.2,setosa
4,5.0,3.6,1.4,0.2,setosa


In [8]:
numeric = df.select_dtypes(include=np.number)

print("Mean")
print(numeric.mean())

Mean
sepal_length    5.843333
sepal_width     3.057333
petal_length    3.758000
petal_width     1.199333
dtype: float64


In [9]:
print("Standard Deviation")
print(numeric.std())

Standard Deviation
sepal_length    0.828066
sepal_width     0.435866
petal_length    1.765298
petal_width     0.762238
dtype: float64


In [10]:
print("Correlation Matrix")
print(numeric.corr())

Correlation Matrix
              sepal_length  sepal_width  petal_length  petal_width
sepal_length      1.000000    -0.117570      0.871754     0.817941
sepal_width      -0.117570     1.000000     -0.428440    -0.366126
petal_length      0.871754    -0.428440      1.000000     0.962865
petal_width       0.817941    -0.366126      0.962865     1.000000


In [11]:
print("Mean")
print(numeric.mean())

print("\nStandard Deviation")
print(numeric.std())

print("\nCorrelation")
print(numeric.corr())

Mean
sepal_length    5.843333
sepal_width     3.057333
petal_length    3.758000
petal_width     1.199333
dtype: float64

Standard Deviation
sepal_length    0.828066
sepal_width     0.435866
petal_length    1.765298
petal_width     0.762238
dtype: float64

Correlation
              sepal_length  sepal_width  petal_length  petal_width
sepal_length      1.000000    -0.117570      0.871754     0.817941
sepal_width      -0.117570     1.000000     -0.428440    -0.366126
petal_length      0.871754    -0.428440      1.000000     0.962865
petal_width       0.817941    -0.366126      0.962865     1.000000
